#pip install reportlab
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def createpdf(filename):
    c=canvas.Canvas(filename,pagesize=letter)
    c.drawString(100,750,"Hello, this is my first PDF")
    c.line(100,740,400,740)
    c.drawString(100,720,"This PDF is generated by Python")
    c.save()


createpdf("praffull.pdf")